[#ftl]
<!DOCTYPE html>
<html lang="cs">
<head>
    <meta charset="UTF-8">
    <title>Ruleta</title>
    <meta content="width=device-width, initial-scale=1" name="viewport">
    <link href="https://fonts.gstatic.com" rel="preconnect">
    <link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,400;0,700;1,400;1,700&display=swap" rel="stylesheet">
    <link href="/images/favicon.png" rel="icon" type="image/png">
</head>
<body>
<div>
    <div>
        <img class="ruleta" src="/images/ruleta-${ruleta}.svg"/>
    </div>
    <div>Dnes večer budeme: <span>${ruleta}</span></div>
</div>
</body>
</html>